---
- name: Playbook to request Red Hat's image builder service to create new ova images
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Check if image exists already
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: check-images-exist

    - name: Get refresh token
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-refresh-token

    - name: Request creation of images
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: request-image-creation

    - name: Get refresh token
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-refresh-token

    - name: Get available composes
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-composes

    - name: Verify composes finished
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: verify-compose-finished

    - name: Download images
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: download-images

    - name: Upload to VCenter
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: deploy-to-vmware
