---
packages:
  - ipa-client
  - yum-utils
  - firewalld

# The actual images definition
images:
  - name: rhel-9-shadowman
    compose:
      distribution: rhel-9
      image_description: rhel9_64Guest
      image_type: vsphere-ova
      customizations:
        packages: "{{ packages }}"
        users:
          - name: "{{ username | default(omit) }}"
            password: "{{ userpassword | default(omit) }}"
            ssh_key: "{{ ssh_key | default(omit) }}"
        firewall:
          services:
            enabled:
              - ssh
        services:
          enabled:
            - firewalld

  - name: rhel-8-shadowman
    compose:
      distribution: rhel-8
      image_description: rhel8_64Guest
      image_type: vsphere-ova
      customizations:
        packages: "{{ packages }}"
        users:
          - name: "{{ username | default(omit) }}"
            password: "{{ userpassword | default(omit) }}"
            ssh_key: "{{ ssh_key | default(omit) }}"
        firewall:
          services:
            enabled:
              - ssh
        services:
          enabled:
            - firewalld
