---
packages:
  - ipa-client
  - yum-utils
  - firewalld

# The actual images definition
images:
  - name: rhel-9-shadowman
    compose:
      distribution: rhel-9
      image_description: rhel9_64Guest
      customizations:
        packages: "{{ packages }}"
        users:
          - name: "{{ username | default(omit) }}"
            password: "{{ userpassword | default(omit) }}"
            ssh_key: "{{ ssh_key | default(omit) }}"
        firewall:
          services:
            enabled:
              - ssh
        services:
          enabled:
            - firewalld
      image_requests:
        - architecture: x86_64
          image_type: vsphere-ova
          size: 53687091200
          upload_request:
            type: aws.s3
            options: '{}'

  - name: rhel-8-shadowman
    compose:
      distribution: rhel-8
      image_description: rhel8_64Guest
      customizations:
        packages: "{{ packages }}"
        users:
          - name: "{{ username | default(omit) }}"
            password: "{{ userpassword | default(omit) }}"
            ssh_key: "{{ ssh_key | default(omit) }}"
        firewall:
          services:
            enabled:
              - ssh
        services:
          enabled:
            - firewalld
      image_requests:
        - architecture: x86_64
          image_type: vsphere-ova
          size: 53687091200
          upload_request:
            type: aws.s3
            options: {}
