---
- name: Request creation of images
  ansible.builtin.uri:
    url: "{{ api_endpoint }}/compose"
    method: POST
    headers:
      Authorization: Bearer {{ refresh_token.json.access_token }}
    body:
      image_name: "{{ image.name }}"
      image_description: "{{ image.compose.image_description | default(omit) }}"
      distribution: "{{ image.compose.distribution }}"
      customizations: "{{ image.compose.customizations | default(omit) }}"
      image_requests: "{{ image.compose.image_requests }}"
    body_format: json
    status_code: 201
  register: compose_request
  loop: "{{ filecheck.results }}"
  loop_control:
    label: "{{ image.name }}"
  vars:
    image: "{{ item.item }}"
  when: not item.stat.exists
